# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ldrb
author: Henrik Finsberg
logo: logo.png
copyright: "2022"

# Cache output from notebooks.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 3000 # We should increase this when we actually want to publish

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  thebe: true

# Information about where the book exists on the web
repository:
  url: https://github.com/finsberg/ldrb # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: <a href="https://www.simula.no/research/projects/department-computational-physiology">Computational Physiology at Simula</a>

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
